"""add phone number to users

Revision ID: 2ba745de7bb0
Revises: 37376ba9b0a6
Create Date: 2026-03-03 11:52:39.303110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba745de7bb0'
down_revision: Union[str, Sequence[str], None] = '37376ba9b0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'phone_number')
    # ### end Alembic commands ###
